### PR TITLE
Add Sourcery config

### LINKED ISSUE #11: Add Sourcery config file
### Summary

Sourcery helps you write better code by using AI to suggest refactors.

### Why?

Better code = better life.

### Ideal implementation

Auto-generated one will be fine, making sure to set the min Python version to 3.8.

### Additional information

_No response_

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

### PR DESCRIPTION
**Pull request by parafoxia**
Closes #11.

### CODE REVIEW

**Review by Jonxslays — APPROVED** [review]
Noice

**Comment by Jonxslays** [comment]
Does it have to be .yaml? or can we shorten to .yml?

**Comment by parafoxia** [comment]
> Does it have to be .yaml? or can we shorten to .yml?

Does it matter?

**Comment by Jonxslays** [comment]
> > Does it have to be .yaml? or can we shorten to .yml?
> 
> Does it matter?

No, not really. I'd just like to keep the extensions the same if possible (e.g. our github actions yaml files are .yml)

**Comment by parafoxia** [comment]
I would guess it probably only checks for the one extension -- it's irritating there's two possible ones, but there no easy way to check if it likes the yml or not, cos it can technically run without it, just not with the defaults we want.

**Comment by Jonxslays** [comment]
Yeah it looks like it does have to be .yaml. No worries. https://docs.sourcery.ai/Reference/Configuration/Sources/

**Pull request merged**
