### PR TITLE
Add nox pipelines

### LINKED ISSUE #7: Add nox pipelines
This can be done prior to setting up the actual CI automation of the pipelines.

References:

- https://github.com/parafoxia/analytix/blob/main/noxfile.py
- https://github.com/Jonxslays/wom.py/blob/master/noxfile.py
- https://github.com/Jonxslays/wom.py/blob/master/scripts/alls.py

Prerequisites:

- #6

### PR DESCRIPTION
**Pull request by parafoxia**
This PR:

* Adds nox pipelines
* Adds the `alls.py` script from wom.py repo -- I went with BSD for that to appease nox, but if you prefer, we can license under its original MIT and update the nox session
* Added a cheeky banner to the `py -m severn` call

Closes #7.

### CODE REVIEW

**Comment by Jonxslays** [comment]
I'm fine licensing it under BSD. Will take a proper look momentarily.

**Comment by parafoxia** [comment]
> I'm fine licensing it under BSD. Will take a proper look momentarily.

Cool beans. Also happy changing it to just be your name seen as it's all your work lmao, but will leave that up to you.

**Comment by Jonxslays** [comment]
> Cool beans. Also happy changing it to just be your name seen as it's all your work lmao, but will leave that up to you.

That's not a big deal I figure we should both be on every py file in this repo.

**Review by Jonxslays — DISMISSED** [review]
Looks good, although ruff doesn't like the length of the banner. May need to disable the check there.

```sh
severn/__main__.py:35:89: E501 Line too long (90 > 88 characters)
severn/__main__.py:36:89: E501 Line too long (89 > 88 characters)
Found 2 errors.
```

**Comment by parafoxia** [comment]
Giant F, didn't check that.

**Review by Jonxslays — APPROVED** [review]

**Pull request merged**
